# Generated by Django 2.1.5 on 2020-06-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerplatters',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='regularpizza',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salads',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sicilianpizza',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='subs',
            name='price',
            field=models.FloatField(),
        ),
    ]
