# Generated by Django 2.1.5 on 2020-06-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200612_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerplatters',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default='Small', max_length=5),
        ),
        migrations.AddField(
            model_name='subs',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default='Small', max_length=5),
        ),
    ]
